// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCstXt19IaNVVC2rbupOAuz64iZYE4AZNA',
    appId: '1:37988486445:web:edcc534c779ffa9afdd7a4',
    messagingSenderId: '37988486445',
    projectId: 'new-task-manager-app',
    authDomain: 'new-task-manager-app.firebaseapp.com',
    storageBucket: 'new-task-manager-app.firebasestorage.app',
    measurementId: 'G-WTLPPJHG3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8w0oSQn0Z5qUEDmR_rihiZLhY8b_vM_g',
    appId: '1:37988486445:android:9f05ab431e8db047fdd7a4',
    messagingSenderId: '37988486445',
    projectId: 'new-task-manager-app',
    storageBucket: 'new-task-manager-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA_xdKpoU8nZOM7jnVOKlusDUEF0zG0Ts',
    appId: '1:37988486445:ios:10ca86fd677a50d7fdd7a4',
    messagingSenderId: '37988486445',
    projectId: 'new-task-manager-app',
    storageBucket: 'new-task-manager-app.firebasestorage.app',
    iosBundleId: 'com.example.newTaskManagerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA_xdKpoU8nZOM7jnVOKlusDUEF0zG0Ts',
    appId: '1:37988486445:ios:10ca86fd677a50d7fdd7a4',
    messagingSenderId: '37988486445',
    projectId: 'new-task-manager-app',
    storageBucket: 'new-task-manager-app.firebasestorage.app',
    iosBundleId: 'com.example.newTaskManagerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCstXt19IaNVVC2rbupOAuz64iZYE4AZNA',
    appId: '1:37988486445:web:0f88dc4e4492198bfdd7a4',
    messagingSenderId: '37988486445',
    projectId: 'new-task-manager-app',
    authDomain: 'new-task-manager-app.firebaseapp.com',
    storageBucket: 'new-task-manager-app.firebasestorage.app',
    measurementId: 'G-JJCD93TZR6',
  );
}
